### ISSUE TITLE
IPP_OP_PAPPL_FIND_DEVICES crashed

### ISSUE THREAD

**Issue by szlt5** [michaelrsweet/pappl#296]
**Describe the bug**
The legacy-printer-app crashed when run below command:
`legacy-printer-app devices`

The call stack as below
```
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:76
#1  0x00007ffff7aa6782 in __GI___strdup (s=s@entry=0x0) at ./string/strdup.c:41
#2  0x00007ffff7cb1ae9 in _papplDeviceInfoCallback (device_info=device_info@entry=0x7fffe77f83b8 "Unknown Printer (Network Printer iR2200i)", device_uri=<optimized out>, 
    device_id=0x0, devices=devices@entry=0x7fffd8012c00) at device.c:582
#3  0x00007ffff7cb30bd in pappl_snmp_find (cb=0x7ffff7cb1a9a <_papplDeviceInfoCallback>, data=0x7fffd8012c00, sock=sock@entry=0x7fffe77f8d00, err_cb=<optimized out>, 
    err_data=0x5555555ab8b0) at device-network.c:1000
#4  0x00007ffff7cb3aa8 in pappl_snmp_list (cb=<optimized out>, data=<optimized out>, err_cb=<optimized out>, err_data=<optimized out>) at device-network.c:1108
#5  0x00007ffff7cb1d31 in papplDeviceList (types=types@entry=255, cb=0x7ffff7cb1a9a <_papplDeviceInfoCallback>, data=data@entry=0x7fffd8012c00, 
    err_cb=0x7ffff7cbf23d <papplLogDevice>, err_data=0x5555555ab8b0) at device.c:721
#6  0x00007ffff7cdf149 in ipp_find_devices (client=0x5555560f9490) at system-ipp.c:594
#7  _papplSystemProcessIPP (client=0x5555560f9490) at system-ipp.c:143
#8  0x00007ffff7caeb69 in _papplClientProcessIPP (client=client@entry=0x5555560f9490) at client-ipp.c:234
#9  0x00007ffff7cad87e in _papplClientProcessHTTP (client=client@entry=0x5555560f9490) at client.c:435
#10 0x00007ffff7cadba0 in _papplClientRun (client=0x5555560f9490) at client.c:668
#11 0x00007ffff7a8f6ba in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:444
#12 0x00007ffff7b1e0d0 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

The "Canon iR2200i" may be a SNMP printer simulator (I guess), so the device id is empty.
And the output for /usr/lib/cups/backend/SNMP as below
```
$ sudo ./snmp 
network lpd://172.16.104.72:515/PASSTHRU "EPSON WF-C5790 Series" "EPSON WF-C5790 Series" "MFG:EPSON;CMD:ESCPL2,BDC,D4,D4PX,ESCPR7,PJL,EJL,PCL,PCLXL,POSTSCRIPT,END4,GENEP;MDL:WF-C5790 Series;CLS:PRINTER;DES:EPSON WF-C5790 Series;CID:EpsonRGB;FID:FXA,DPA,WFA,ETA,AFA,DAA,WRA;RID:50;DDS:0263E0;ELG:1180;SN:583342443030393811;" ""
network socket://172.16.2.210 "Canon iR2200i" "Canon iR2200i" "" "Canon Toride B1 3F"
```

**Comment by michaelrsweet** [comment]
[master cea2db4] Fix device list crash (Issue #296)

[v1.4.x dd58909] Fix device list crash (Issue #296)
